### ISSUE TITLE
Breadcrumbs: Discuss in general, they were not included in the designs

### ISSUE THREAD

**Issue by kjays** [lauriii/umami#126]
https://www.drupal.org/project/drupal/issues/2904243#comment-12405148

**Comment by markconroy** [comment]
For now, I am going to set breadcrumbs to not display on the homepage, but to display on all other pages. 

This is a config change, so the code for that will be in the demo_umami repo.

**Comment by markconroy** [comment]
Breadcrumbs removed here - https://github.com/gareth-fivemile/demo_umami/commit/7a21f7edb055af1ad6b40006d0ac1cdd9fe6d531

Not sure if that fixes the issue - for some reason I can't see breadcrumbs on homepage on safari, chrome, or firefox.

**Comment by markconroy** [comment]
I've made some more changes to this, so that now the current page title is amended as a final (unlinked) breadcrumb.

[it's on this commit](https://github.com/lauriii/umami/commit/84560053652a56b0f761d1b850249ae6fd6708f0)

![screen shot 2018-01-05 at 20 51 12](https://user-images.githubusercontent.com/2183332/34627911-54f31ee0-f25a-11e7-8840-7b527c290b87.png)

**Comment by fuzzbomb** [comment]
For accessibility, they help to address WCAG [SC 2.4.8 Location](https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-location.html)

SC 2.4.8 is at WCAG level AAA, so technically we don't have to address it for our accessibility gate.  I'd prefer to include it though, since Umami is about showcasing Drupal's features, which includes accessibility.

An alternative technique to address SC 2.4.8 is to provide a site-map, however Drupal core doesn't provide an easy way to do that, whereas breadcrumbs do come as part of core.
