### ISSUE TITLE
 Components: System Messages

### ISSUE THREAD

**Issue by markconroy** [lauriii/umami#48]
Related: #114

**Comment by kjays** [comment]
![umami - tabs with status msg - error](https://user-images.githubusercontent.com/31449148/32345057-f6a6ddbc-c000-11e7-822b-09496d645988.jpg)
![umami - tabs with status msg - status](https://user-images.githubusercontent.com/31449148/32345058-f6ca4c84-c000-11e7-9424-06f7e72f079e.jpg)
![umami - tabs with status msg - warning](https://user-images.githubusercontent.com/31449148/32345059-f6e0ad8a-c000-11e7-8648-084a07fde700.jpg)

**Status:**
Band background colour: #E6EEE0
Text: #000000
Links: #CC2A00

**Warning**
Band background colour: #FCF1D4
Text: #000000
Links: #CC2A00

**Error**
Band background colour: #F9E6EB
Text: #000000
Links: #CC2A00

And I wouldn't be surprised if we need to add some custom icons for accessibility since colour alone might not cut it.

**Comment by ckrina** [comment]
+1 to adding icons for accessibility. @kjays do you agree?

**Comment by markconroy** [comment]
If we are using classy as a base theme do we not automatically have those icons coming in?

**Comment by thamas** [comment]
You are right @markconroy. This is how it looks like on the example page of the styleguide module (I used that to test this issue).

![screenshot-2017-12-09 23-34-12](https://user-images.githubusercontent.com/1244043/33800075-7c6edbf2-dd39-11e7-955a-1954fef6f3f9.png)

Do we like that, or want to design something different @kjays / @jakestir ?

**Comment by kjays** [comment]
I'm working on reworking these for the accessibility feedback

**Comment by thamas** [comment]
Related: #114

**Comment by thamas** [comment]
![screenshot-2017-12-28 18-20-00](https://user-images.githubusercontent.com/1244043/34417973-c3343520-ebfb-11e7-881b-fc42ad3fcb76.png)

**Comment by thamas** [comment]
I think it is done! :)
@kjays FYI I kept the text decoration on links because I hope it makes them more accessible.
